site_name: TKAI Lab

# Repository
repo_name: TKAI-Lab
repo_url: https://github.com/TKAI-LAB-Mali

# Site configuration
theme:
  name: material
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette: 
    # light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search

# Site organization
nav:
  - Home: index.md
  - People: people.md
  - Projects: projects.md
  - Publications: publications.md
  - Join Us: join.md
  - Contact: contact.md
