site_name: TKAI Lab
repo_name: TKAI-Lab
repo_url: https://github.com/TKAI-LAB-Mali

theme:
  logo: assets/images/lab-logo.png
  name: material
  custom_dir: overrides
  favicon: assets/images/lab-logo.png
  features:
  # - navigation.instant
  # - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
  # Light mode configuration
  - media: "(prefers-color-scheme: light)"
    # scheme: default
    primary: custom
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode

  # Dark mode configuration
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: custom
    toggle:
      icon: material/weather-night
      name: Switch to light mode


plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/extra.js
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - News: news.md
  - People: people.md
  - Research: research.md
  - Publications: publications.md
  - Academic Genealogy: genealogy.md
  - Moments : moments.md
  - Join Us: join.md
